sudo: false

language: python

python:
- '3.4'

services:
- postgresql

addons:
  postgresql: "9.4"

env:
  global:
  - DB_USER=postgres

cache:
  directories:
  - $HOME/.cache/pip

install:
- pip install -r requirements.txt
- python setup.py develop

before_script:
- psql -U postgres -c "create extension postgis"
- psql -U postgres -c "create extension hstore"

script: py.test
